/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quan.ly.giao.vien;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Latitude 5570
 */
public class FormGV extends javax.swing.JFrame {
    
   EmpList teacher = new EmpList();
   static int position =0;
    
    /**
     * Creates new form FormGV
     */
    public FormGV() {
        initComponents();
        setLocationRelativeTo(null);
        fillTable();
    }
    
    /*
      // Phương thức gán dữ liệu tên cho đúng cột trong bảng
    private void fillTable() {
        
       
      DefaultTableModel tableModel = 
                (DefaultTableModel) txtbang.getModel();
// Xóa tất cả các hàng
tableModel.setRowCount(0);

        for (Employee listt : teacher.getALLGV()) {
           
            tableModel.addRow(new Object[]{listt.getMaGV(), listt.getTenGV(),
                listt.getNgaySinh(),
               
                listt.isGioiTinh(),
                listt.getDiaChi(),
                listt.getPhongBan(),
               
            });
        }
        // Cập nhật dữ liệu
        tableModel.fireTableDataChanged();

    }*/
  
    
    public void fillTable(){
        DefaultTableModel tbModel = 
                (DefaultTableModel) txtbang.getModel();
        tbModel.setRowCount(0);
        for (Employee listt : teacher.getALLGV()) {
            
            Object [] rowData = new Object[6];
            rowData[0] = listt.getMaGV();
            rowData[1] = listt.getTenGV();
            rowData[2] = listt.getNgaySinh();
            String gt = "Nữ";
            if(listt.isGioiTinh()){
                gt ="Nam";
            }
            
            rowData[3] = gt;
            rowData[4] = listt.getDiaChi();
            rowData[5] = listt.getPhongBan();
             tbModel.addRow(rowData);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtngaySinh = new javax.swing.JTextField();
        txtdiaChi = new javax.swing.JTextField();
        txtma = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtboMon = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        txttimKiem = new javax.swing.JButton();
        txtThem = new javax.swing.JButton();
        txtLuu = new javax.swing.JButton();
        txtSua = new javax.swing.JButton();
        txtXoa = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtThoat = new javax.swing.JButton();
        txtthongTin = new javax.swing.JLabel();
        txtCount = new javax.swing.JLabel();
        txtve = new javax.swing.JButton();
        txttiep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Quản Lý Giáo Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã GV:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ Và Tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày Sinh:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giới Tính:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa Chỉ:");

        buttonGroup1.add(rdNam);
        rdNam.setSelected(true);
        rdNam.setText("Nam");

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Bộ Môn:");

        txtboMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toán", "Ngôn Ngữ Anh", "Công Nghệ Thông Tin", "Thể Chất", "Hóa Học", "Triết Học" }));

        txttimKiem.setBackground(new java.awt.Color(204, 204, 204));
        txttimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttimKiem.setForeground(new java.awt.Color(255, 51, 51));
        txttimKiem.setText("Tìm Kiếm");
        txttimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimKiemActionPerformed(evt);
            }
        });

        txtThem.setBackground(new java.awt.Color(204, 204, 204));
        txtThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtThem.setForeground(new java.awt.Color(255, 51, 51));
        txtThem.setText("Thêm Mới");
        txtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemActionPerformed(evt);
            }
        });

        txtLuu.setBackground(new java.awt.Color(204, 204, 204));
        txtLuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLuu.setForeground(new java.awt.Color(255, 51, 51));
        txtLuu.setText("Lưu");
        txtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuuActionPerformed(evt);
            }
        });

        txtSua.setBackground(new java.awt.Color(204, 204, 204));
        txtSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSua.setForeground(new java.awt.Color(255, 51, 51));
        txtSua.setText("Sửa");
        txtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuaActionPerformed(evt);
            }
        });

        txtXoa.setBackground(new java.awt.Color(204, 204, 204));
        txtXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtXoa.setForeground(new java.awt.Color(255, 51, 51));
        txtXoa.setText("Xóa");
        txtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXoaActionPerformed(evt);
            }
        });

        txtThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtThoat.setText("Thoát");
        txtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoatActionPerformed(evt);
            }
        });

        txtthongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtthongTin.setText("Thông báo:");

        txtCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCount.setText("Tổng số giáo viên:");

        txtve.setText("Trở về");
        txtve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtveActionPerformed(evt);
            }
        });

        txttiep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttiep.setText("Tiếp");
        txttiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttiepActionPerformed(evt);
            }
        });

        txtbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã GV", "Họ tên GV", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Bộ Môn"
            }
        ));
        txtbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtbang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttimKiem)
                .addGap(39, 39, 39)
                .addComponent(txtThem)
                .addGap(45, 45, 45)
                .addComponent(txtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTen)
                            .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtboMon, 0, 307, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdNam)
                                .addGap(39, 39, 39)
                                .addComponent(rdNu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtthongTin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(txtve)
                        .addGap(152, 152, 152)
                        .addComponent(txttiep))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCount)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThoat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtboMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimKiem)
                    .addComponent(txtThem)
                    .addComponent(txtLuu)
                    .addComponent(txtSua)
                    .addComponent(txtXoa))
                .addGap(36, 36, 36)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtve)
                    .addComponent(txttiep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtthongTin)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoatActionPerformed
        dispose();
    }//GEN-LAST:event_txtThoatActionPerformed

    public void resetForm(){
        txtma.setText("");
        txtTen.setText("");
        txtdiaChi.setText("");
        txtngaySinh.setText("");
        rdNam.setSelected(true);
        txtboMon.setSelectedIndex(0);
        
    }
    private void txtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_txtThemActionPerformed

    
    
    public Employee getModel(){
        Employee epl = new Employee();
        epl.setMaGV(txtma.getText());
        epl.setTenGV(txtTen.getText());
        epl.setDiaChi(txtdiaChi.getText());
        epl.setNgaySinh(txtngaySinh.getText());
        boolean gt = false;
        if(rdNam.isSelected()){
            gt = true;
        }
        epl.setGioiTinh(gt);
        epl.setPhongBan(txtboMon.getSelectedItem().toString());
        return epl;

    }
       public boolean checkValidateForm(){
           if(txtma.getText().isEmpty()||
                txtngaySinh.getText().isEmpty()||
                   txtTen.getText().isEmpty()||
                   txtdiaChi.getText().isEmpty()){
               return false;
           }
              return true;          
       }
            
    private void txtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuuActionPerformed
        // TODO add your handling code here:
        if (checkValidateForm()) {

            Employee e = getModel();
            if (teacher.add(e) > 0) {
                txtthongTin.setText("Cập nhật thành công");
                txtthongTin.setForeground(Color.BLUE);
                txtCount.setText("COUNT: " + teacher.count());
                // Cap nhat du lieu len bang
                
                fillTable();
                
            } else {
                txtthongTin.setText("Cập nhật không thành công");
                txtthongTin.setForeground(Color.RED);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
        }


    }//GEN-LAST:event_txtLuuActionPerformed

    
    public void setModel(Employee lss){
        txtma.setText(lss.getMaGV());
        txtTen.setText(lss.getTenGV());
        txtdiaChi.setText(lss.getDiaChi());
        txtngaySinh.setText(lss.getNgaySinh());
        rdNam.setSelected(lss.isGioiTinh());
        rdNu.setSelected(!lss.isGioiTinh());
        txtboMon.setSelectedItem(lss.getPhongBan());
    }
    
    private void txttimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimKiemActionPerformed
        // TODO add your handling code here:
        if(txtma.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã giáo viên");
       
        }
        else {
            Employee lss = teacher.findBymaGV(txtma.getText());
            if(lss !=null){
                setModel(lss);
            } else {
                txtthongTin.setText("Không tìm thấy  tên giáo viên"+ txtma.getText());
                txtthongTin.setForeground(Color.RED);
            }
        }
        
        
    }//GEN-LAST:event_txttimKiemActionPerformed

    private void txtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuaActionPerformed
        // TODO add your handling code here:
        
        
        if(txtma.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập mã giáo viên");
        }
        else{
            Employee lss = getModel();
            if(teacher.edit(lss)>0){
             txtthongTin.setText("Sửa thông tin giáo viên thành công");
              txtthongTin.setForeground(Color.BLUE);
              fillTable();
                
            } else {
                txtthongTin.setText("Sửa thông tin không thành công");
                txtthongTin.setForeground(Color.RED);
            }
                
           
            }
                
            
        

        
    }//GEN-LAST:event_txtSuaActionPerformed

    private void txtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXoaActionPerformed
        // TODO add your handling code here:
        if(teacher.del(txtma.getText())>0){
            JOptionPane.showMessageDialog(this, "Bạn đã xóa thành công");
        }else {
        
        
                txtthongTin.setText("Không tìm thấy  tên giáo viên"+ txtma.getText());
                txtthongTin.setForeground(Color.RED);
    
        }
        
        fillTable();
    }//GEN-LAST:event_txtXoaActionPerformed

    private void txtveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtveActionPerformed
        // TODO add your handling code here:
        position --;
        if(position <=0){
            position =0;
        }
        setModel(teacher.getoneEmloyeAtPosition(position));
        
    }//GEN-LAST:event_txtveActionPerformed

    private void txttiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttiepActionPerformed
        // TODO add your handling code here:
         position ++;
        if(position >= teacher.count()){
            position =teacher.count() - 1;
        }
        setModel(teacher.getoneEmloyeAtPosition(position));
    }//GEN-LAST:event_txttiepActionPerformed

    private void txtbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbangMouseClicked
        // TODO add your handling code here:
        int point = txtbang.rowAtPoint(evt.getPoint());
        Employee list = teacher.getoneEmloyeAtPosition(point);
        setModel(list);
    }//GEN-LAST:event_txtbangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JLabel txtCount;
    private javax.swing.JButton txtLuu;
    private javax.swing.JButton txtSua;
    private javax.swing.JTextField txtTen;
    private javax.swing.JButton txtThem;
    private javax.swing.JButton txtThoat;
    private javax.swing.JButton txtXoa;
    private javax.swing.JTable txtbang;
    private javax.swing.JComboBox<String> txtboMon;
    private javax.swing.JTextField txtdiaChi;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtngaySinh;
    private javax.swing.JLabel txtthongTin;
    private javax.swing.JButton txttiep;
    private javax.swing.JButton txttimKiem;
    private javax.swing.JButton txtve;
    // End of variables declaration//GEN-END:variables
}
